### ISSUE TITLE
Asking for pretrained model

### ISSUE THREAD

**Issue by nickle-fang** [OpenPerceptionX/PersFormer_3DLane#25] opened 2022-07-06 02:21 UTC
Could you please release a pre-trained model based on OpenLanes dataset? Thanks very much!

**Comment by ilnehc** [comment] 2022-07-06 03:27
@nickle-fang Hi, since OpenLane is built on the Waymo Open Dataset, we cannot re-distribute pre-trained checkpoints per its license requirement.

**Comment by ilnehc** [comment] 2022-07-06 03:28
Duplicate of https://github.com/OpenPerceptionX/PersFormer_3DLane/issues/18

**Closed by ilnehc** 2022-07-06 03:27 UTC
